apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    namespace: docker-network-ns

spec:

  selector:

       app: mysql-tag
  ports:
    - port: 3306
      targetPort: 3306

  type: ClusterIP