apiVersion: apps/v1
kind: Deployment
metadata:
    name: springboot-deployment
    namespace: docker-network-ns
spec:
  replicas: 2
  

  selector:
      matchLabels:
          app: springboot-tag
  template: 

    metadata:
       labels:
          app: springboot-tag
    spec:

      containers:
          - name: springboot-cont

            image: abhi7754/docker1:d3

            ports:
            - containerPort: 8080
      