apiVersion: v1
kind: Service
metadata:
   name: springboot-service
   namespace: docker-network-ns
spec:
  selector:
     app: springboot-tag	
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
       